version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: local_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev --http-port=8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.example
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/local_delivery
      REDIS_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      ALLOWED_HOSTS: localhost,127.0.0.1,103.177.181.252
      DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - keycloak

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_BASE_URL=http://103.177.181.252:8000
      - VITE_WS_URL=ws://103.177.181.252:8000
      - VITE_KEYCLOAK_URL=http://103.177.181.252:8080
      - VITE_KEYCLOAK_REALM=local-delivery
      - VITE_KEYCLOAK_CLIENT_ID=local-delivery-app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
