apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: local-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: local-delivery-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VITE_API_BASE_URL
              value: http://backend.local
            - name: VITE_WS_URL
              value: ws://backend.local
            - name: VITE_KEYCLOAK_URL
              value: http://keycloak.local-delivery.svc.cluster.local:8080
            - name: VITE_KEYCLOAK_REALM
              value: local-delivery
            - name: VITE_KEYCLOAK_CLIENT_ID
              value: local-delivery-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: local-delivery
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
